### PR TITLE
Drop undershoot indication completely

### PR DESCRIPTION
**Pull request by keynslug**
As upstream did the same somewhere around 3.24.5, see:
https://gitlab.gnome.org/GNOME/gtk/commit/7da52e5255a16f897b5338af1a8ee0445d493056

The rationale outlined in:
https://gitlab.gnome.org/GNOME/gtk/issues/1591

### CODE REVIEW

**Comment by jnsh** [comment]
Thank you. Definitely makes sense to follow upstream on this.

Only one nit: Would you mind prepending the commit message with `gtk3: `, for cleaner and more consistent commit history? Apart from that, this looks good :)

**Comment by jnsh** [comment]
Merged, with small commit message tweak in https://github.com/jnsh/arc-theme/commit/8292b676107ffc437655f8556bb22392396a7f82. Thanks again :)

**Comment by keynslug** [comment]
Oh, sorry for the delay and thanks for merging!

**Comment by jnsh** [comment]
No worries about the delay. I thought I may just as well edit the message myself while I was working on the theme anyway, instead of bothering you about the small detail.

**Pull request closed without merging**
