### PR TITLE
[WIP] Adding gnome-shell 40 support

### PR DESCRIPTION
**Pull request by zeten30**
Gnome-shell 40 initial support. 

- create version directory
- improve meson.build (no minor version like 3.38, just keep the major and ignore X.rc - release candidate)
- fix panel buttons & dash

### CODE REVIEW

**Comment by zeten30** [comment]
@jnsh Hi, no problems with the long reply. I've expected it and that's why I've marked it as WIP. 

I'm glad that you like the meson.build stuff. I'm also fine with completing gnome-shell 40 port completely or as a collaboration (if your fine with helping me with it).

If I understand it correctly we want to break it into smaller commits, correct? Something like:

1. add support to meson
2. create a directory structure for version 40
3. 4,5 change scss files..

Actual style changes are tiny.

```
$ diff 3.38.scss 40.scss
891c891
<       border-bottom-width: 1px;
---
>       border: 0 0 1px 0;
892a893,894
>       border-radius: $panel-corner-radius;
>       box-shadow: none;
898a901,902
>       border: 0 0 1px 0;
>       border-radius: $panel-corner-radius;
900d903
<       border-bottom-width: 1px;
1768a1772
>   background-image: none;
1797c1801,1804
<   &, &:rtl, .right & { padding: 4px 8px; }
---
>   &, &:rtl, .right & { 
>     padding: 4px 8px; 
>     border-radius: 0;
>   }
1799c1806,1814
<   .top &, .bottom & { padding: 6px; }
---
>   .top &, .bottom & { 
>     padding: 6px;
>     border-radius: 0; 
>   }
> }
> 
> .dash-background {
>   background-color: transparent;
>   border-radius: 0 
2132a2148
>   background-image: none;
```

It fixes weird shadows and rounded corners on panel buttons & dash. The only think I'm little struggling with is rounded corners of workspaces in overview.

**Comment by jnsh** [comment]
> If I understand it correctly we want to break it into smaller commits, correct? Something like:
> 
>     1. add support to meson
> 
>     2. create a directory structure for version 40
> 
>     3. 4,5 change scss files..
Pretty much so. Step 2 should also include copying over the shell theme files from previous version i.e. `cp -a common/gnome-shell/3.38 common/gnome-shell/40`, but I think this was already clear :)

For the changes to SCSS files and other theme files, it really is best to methodologically go trough the upstream changes starting from the oldest commits, to make sure nothing is missed, and to keep the Arc SCSS in sync with upstream. This also helps the review process and any collaborative working, when it's made clear which upstream changes have been addressed.

If there are multiple upstream commits effecting a single shell element (e.g. for dash), it might make sense to group the changes to a single commit for Arc. Also some changes may have already been backported to earlier versions, and therefore to Arc. Also there could be some changes that simply aren't necessary for Arc for some reason.

I have quite a lot of work I'd like to get finished ASAP for Arc, so I'm happy with any amount of help on this. Feel free to ask for any advice, or if anything gets too difficult, you can leave it to me. Again, the main thing is to be clear about which upstream changes have been addressed.

I don't see anything wrong with the SCSS diff you posted, but I can't be certain without looking up references to the upstream changes. Also I don't have GNOME 40 installation set up yet, so I can't actually test the changes at this time.

**Comment by jnsh** [comment]
So I finally managed to get GNOME 40 installed for testing...

I think the theme update will be quite a bit trickier this time than usual. This is not necessarily for technical reasons, but there are some design-related decisions and tweaks or fixes that aren't simple if you haven't worked on the theme before. Therefore it may be easier if I'll finish the porting myself this cycle, especially since I'd like to get the update out around the time of the stable GNOME 40 release, which is only 5 days away..

If you have already made a lot of progress ahead after the initial PR, I can review that, and continue the work myself from there. From the current PR, I could merge the meson.build update, if you clean up the commit from other changes, and update the commit message.

Sorry about the hassle. I greatly appreciate your effort in any case.

**Comment by zeten30** [comment]
@jnsh understood:) So far, my focus was only on fixing 'rounded corners' and 'shadows' for panel buttons. Nothing fancy.

I've removed everything besides meson.build.

**Comment by zeten30** [comment]
My changes. Just for reference. 
[_common.zip](https://github.com/jnsh/arc-theme/files/6169509/_common.zip)

**Comment by jnsh** [comment]
I merged the `meson.build` changes as part of the initial GNOME 40 updates, although I made a few more cosmetic tweaks, and separated the addition to the `gnome_shell_versions` array from this commit.

Thanks again!

**Pull request closed without merging**
