### PR TITLE
Improved topbar readability

### PR DESCRIPTION
**Pull request by danielsouzat**
Slight bigger font and slight slimmer bar. Top bar font was appearing smaller than title bar one.

### CODE REVIEW

**Comment by jnsh** [comment]
Can you elaborate more on the purpose of this change, i.e. what it is supposed to fix or improve? and maybe post a before/after screenshots? I understand that increasing the panel font size would improve readability, but for one, this change makes it inconsistent with the rest of the theme. Also, I don't think you provided any rationale for reducing the panel height.

Additionally, I just increased the overall gnome-shell font size in https://github.com/jnsh/arc-theme/commit/e672981af6dff3e7896310aa8118ff01624a9538, and users were always able to further adjust it to their liking via the global font scaling settings.

> Top bar font was appearing smaller than title bar one.

If you mean the window titlebars, their font size can be changed by users e.g. from gnome-tweaks.

**Comment by danielsouzat** [comment]
Sure! The rationale is that the theme is not scaling the top bar font with the systems fonts. At least not with the ones you can set with gnome-tweaks. But you're right about the inconsistency. I hardcoded a value and that would work exclusively for me.

I suggest this instead:
 
```css
 font-size: $font-size * 1.5px;
 height: $font-size * 1.5px + 12px;
```

It will slightly increase top bar font size relatively to global font-size and use it to achieve practically the original top bar height.
Still, I don't know if it would solve the general problem because I don't know how to scale it with font-size set by gnome-tweaks.

You can find screenshots at my fork's README.

https://github.com/danielsouzat/arc-theme

**Comment by jnsh** [comment]
> Sure! The rationale is that the theme is not scaling the top bar font with the systems fonts.

This applies for the whole shell theme, not just the top bar.
The gnome shell font sizes can't be directly changed by users, but this can be worked around using the font scaling settings via e.g. gnome-tweaks (in Fonts -> Scaling factor).

If I understood correctly, that should solve the problem you're trying to work around with this.

> You can find screenshots at my fork's README.

I specifically asked for pre/post screenshots on your system to get better idea what you're trying to improve here. Comparing this kind of changes to the theme from screenshots on different system with different font settings doesn't help. It would have been polite to at least post/link the screenshots here instead of asking to check your repo.

**Comment by danielsouzat** [comment]
Did not want to be unpolite. I'm not used to PR or PR at GitHub and really did not know I could attach files here.

before
after

Scaling factor is not really a good workaround as it will scale everything and not just top bar font. But it's alright. It is your project and if you think it's fine as it is, then it's fine. I'm okay with modding minor things to my personal preference.

**Pull request closed without merging**
